In [2]:
import seaborn as sns
df=sns.load_dataset('titanic')

In [3]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [4]:
df.info

<bound method DataFrame.info of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_m

In [29]:
df['sex']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: sex, Length: 891, dtype: int32

In [30]:
np.where(df['sex']=='male',1,0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [23]:
df

sex  embarked  alone  pclass  survived
0      0         0      0       3         0
1      0         1      0       1         1
2      0         0      1       3         1
3      0         0      0       1         1
4      0         0      1       3         0
..   ...       ...    ...     ...       ...
886    0         0      1       2         0
887    0         0      1       1         1
888    0         0      0       3         0
889    0         1      1       1         1
890    0         2      1       3         0

[891 rows x 5 columns]

In [31]:
###let's perform lable encoding on sex column
import numpy as np
# df['sex']=np.where(df['sex']=='male',1,0)
###let's perform label encoding on embarked
ordinal_label ={k:i for i,k in enumerate(df['embarked'].unique(),0)}
df['embarked']=df['embarked'].map(ordinal_label)

C:\Users\77819\AppData\Local\Temp\ipykernel_15852\3202118878.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['embarked']=df['embarked'].map(ordinal_label)


In [32]:
df['sex']

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: sex, Length: 891, dtype: int32

In [33]:
ordinal_label

{0: 0, 1: 1, 2: 2, 3: 3}

In [34]:
df

sex  embarked  alone  pclass  survived
0      0         0      0       3         0
1      0         1      0       1         1
2      0         0      1       3         1
3      0         0      0       1         1
4      0         0      1       3         0
..   ...       ...    ...     ...       ...
886    0         0      1       2         0
887    0         0      1       1         1
888    0         0      0       3         0
889    0         1      1       1         1
890    0         2      1       3         0

[891 rows x 5 columns]

In [35]:
#let's perform label encoding on alone
df['alone']=np.where(df['alone']==True,1,0)

C:\Users\77819\AppData\Local\Temp\ipykernel_15852\3616920296.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['alone']=np.where(df['alone']==True,1,0)


In [36]:
##['sex','enumerate','alone','pclass','survived']
df=df[['sex','embarked','alone','pclass','survived']]
df.head()

sex  embarked  alone  pclass  survived
0    0         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    0         0      1       3         0

In [37]:
df

sex  embarked  alone  pclass  survived
0      0         0      0       3         0
1      0         1      0       1         1
2      0         0      1       3         1
3      0         0      0       1         1
4      0         0      1       3         0
..   ...       ...    ...     ...       ...
886    0         0      1       2         0
887    0         0      1       1         1
888    0         0      0       3         0
889    0         1      1       1         1
890    0         2      1       3         0

[891 rows x 5 columns]

In [38]:
#train Test split is usually done to avoid overfitting
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df[['sex','embarked','alone','pclass']],
                                                  df['survived'],test_size=0.3,random_state=100)

In [39]:
X_train

sex  embarked  alone  pclass
69     0         0      0       3
85     0         0      0       3
794    0         0      1       3
161    0         0      1       2
815    0         0      1       1
..   ...       ...    ...     ...
855    0         0      0       3
871    0         0      0       1
835    0         1      0       1
792    0         0      0       3
520    0         0      1       1

[623 rows x 4 columns]

In [40]:
X_train.isnull().sum()

sex         0
embarked    0
alone       0
pclass      0
dtype: int64

In [41]:
##perform chi2 test
from sklearn.feature_selection import chi2

In [42]:
chi2(X_train,y_train)# chi2 returns 2 values ********Fscore and the p_valu

(array([        nan,  7.55053653, 10.88471585, 21.97994154]),
 array([           nan, 5.99922095e-03, 9.69610546e-04, 2.75514881e-06]))